//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeeMachine.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CoffeeMachine.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cappucino.
        /// </summary>
        public static string StringIdCappucino {
            get {
                return ResourceManager.GetString("StringIdCappucino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chocolat.
        /// </summary>
        public static string StringIdChocolate {
            get {
                return ResourceManager.GetString("StringIdChocolate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Café.
        /// </summary>
        public static string StringIdCoffee {
            get {
                return ResourceManager.GetString("StringIdCoffee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crème.
        /// </summary>
        public static string StringIdCream {
            get {
                return ResourceManager.GetString("StringIdCream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expresso.
        /// </summary>
        public static string StringIdExpresso {
            get {
                return ResourceManager.GetString("StringIdExpresso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allongé.
        /// </summary>
        public static string StringIdLongCoffee {
            get {
                return ResourceManager.GetString("StringIdLongCoffee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lait.
        /// </summary>
        public static string StringIdMilk {
            get {
                return ResourceManager.GetString("StringIdMilk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sucre.
        /// </summary>
        public static string StringIdSugar {
            get {
                return ResourceManager.GetString("StringIdSugar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thé.
        /// </summary>
        public static string StringIdTea {
            get {
                return ResourceManager.GetString("StringIdTea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eau.
        /// </summary>
        public static string StringIdWater {
            get {
                return ResourceManager.GetString("StringIdWater", resourceCulture);
            }
        }
    }
}
